server:
    port: 8080


spring:
    datasource:
      maximum-pool-size: 10
      driver-class-name: com.mysql.jdbc.Driver
      auto-commit: true
      connection-test-query: SELECT 1
      connectionTimeout: 10000
      maxLifetime: 180000

mybatis:
  mapper-locations: mapper/*.xml

endpoints:
  enabled: true
  autoconfig:
    enabled: true
  configprops:
    enabled: true
  dump:
    enabled: true
  health:
    enabled: true
  info:
    enabled: true
  metrics:
    enabled: true
  shutdown:
    enabled: true
  restart:
    enabled: true
  env:
    enabled: true
  mappings:
    enabled: true
  beans:
    enabled: true
